### ISSUE TITLE
Add to `golangci-lint`

### ISSUE THREAD

**Issue by zx8** [nishanths/dupeimport#4]
This linter is brilliant!

It would be great to have it included in https://github.com/golangci/golangci-lint with the option to automatically `golangci-lint run --fix` any issues found. 🙂 

I've also created an issue over at https://github.com/golangci/golangci-lint/issues/2070 to see if we can get the ball rolling on this.

**Comment by zx8** [comment]
Never mind, `golangci-lint` maintainers rejected the idea. 😔

**Comment by nishanths** [comment]
Hi @zx8, thank you for sharing. 

In case it helps, the `stylecheck` linter in golangci-lint can report duplicate imports. (But it doesn't fix them.)

In your projects, maybe you could run `dedupimport` once to automatically fix any existing duplicates. Then you could use `stylecheck` to prevent committing files with duplicate imports going forward. 🙂
